name: Bandit Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  security_scan:
    runs-on: ubuntu-latest


    steps:

      - name: Клонировать другой репозиторий
        run: git clone https://github.com/MaksimGolev/vulnpy.git
        
      - name: Установить Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Установить зависимости
        run: |
          cd vulnpy
          pip install --user -r requirements.txt

      - name: Инициализация базы данных
        run: |
          cd bad && python3 db_init.py
          cd ../good && python3 db_init.py
          cd ..

      - name: Установить Bandit
        run: pip install bandit

      - name: Запустить Bandit и сохранить отчёт
        run: |
          cd vulnpy
          bandit -r . -f json -o bandit_report.json || true

      - name: Сохранить отчёт как артефакт
        uses: actions/upload-artifact@v4
        with:
          name: bandit-security-report
          path: vulnpy/bandit_report.json
          
